### ISSUE TITLE
Inappropriate line breaks

### ISSUE THREAD

**Issue by catwang01** [baolong281/jupyter-copilot#9]
Thanks for bringing such a wonderful extension!

But I found that there are some inappropriate line breaks which break the code.

For example:

[here](https://github.com/baolong281/jupyter-copilot/blob/705e80595dd131ecf0370ca8794af5a5dff504cd/jupyter_copilot/lsp.py#L112)

```python
                self.logger.error(f"LSP server process has terminated. Exit code: {
                    self.process.returncode}")
```

This will throw a syntax error in Python 3.10.4. I believe the f-string syntax doesn't allow such line breaks, at least before 3.10.4. 

Removing the line break should fix it:

```python
                self.logger.error(f"LSP server process has terminated. Exit code: { self.process.returncode}")
```

**Comment by baolong281** [comment]
Thanks I really appreciate this! I fixed this and you other issue in the [newest realease](https://pypi.org/project/jupyter-copilot/0.1.2/#files) :)
